name: CI/CD for Full-Stack App
on:
    push:
        branches: [main]
jobs:
    deploy:
        runs-on: ubuntu-latest


        steps:
            - name: Checkout code
              uses: actions/checkout@v3


            - name: SSH into EC2 & Deploy
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.EC2_HOST }} # add your host here
                  username: ubuntu
                  key: ${{ secrets.EC2_SSH_KEY }}
                  port: 22
                  script: |


                      # BACKEND DEPLOYMENT
                      cd /home/ubuntu/backend
                      git pull origin main
                      sudo docker stop frontend || true
                      sudo docker rm frontend || true
                      sudo docker build -t frontend:latest .
                      sudo docker run -d --name frontend -p 5001:5001 frontend:latest
