name: CI/CD for Full-Stack App
on:
    push:
        branches: [main]
jobs:
    deploy:
        runs-on: ubuntu-latest


        steps:
            - name: Checkout code
              uses: actions/checkout@v3


            - name: SSH into EC2 & Deploy
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: 65.0.135.175  # add your host here
                  username: ubuntu
                  key: ${{ secrets.EC2_SSH_KEY }}
                  port: 22
                  script : |
                       df -h
